In [1]:
import numpy as np

In [8]:
#Create matrix
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8]
 [ 9 10]
 [11 12]]


In [6]:
#Matrix Transpose
print("Tranpose of A:\n", A.T)

Tranpose of A:
 [[1 4]
 [2 5]
 [3 6]]


In [9]:
#Dot product (Matrix multiplication)
result = np.dot(A,B)
print("Dot product (A x B):\n", result)

Dot product (A x B):
 [[ 58  64]
 [139 154]]


In [10]:
#Element-wise Multiplication
C = np.array([[1,2], [3,4]])
D = np.array([[5,6], [7,8]])

print("Element-wise multiplication:\n", C*D)

Element-wise multiplication:
 [[ 5 12]
 [21 32]]
