In [2]:
#Importing the numpy library
import numpy as np

In [10]:
#Create arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.arange(10)
arr3 = np.zeros((3,3))
arr4 = np.ones((2,4))

print(arr1)
print(arr2)
print(arr3)
print(arr4)

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
#Basic operations
print("Addition:", arr1 +5)
print("Multiplication:", arr1 * 2)
print("Square:", arr1**2)

Addition: [ 6  7  8  9 10]
Multiplication: [ 2  4  6  8 10]
Square: [ 1  4  9 16 25]


In [12]:
#Statistical Operations
print("Mean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Max:", np.max(arr1))
print("Min:", np.min(arr1))

Mean: 3.0
Sum: 15
Max: 5
Min: 1


In [ ]:
#Reshape
reshaped = np.arange(12).reshape(3,4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
#Indexing & Slicing
print(arr1[2])
print(arr1[1:4])

3
[2 3 4]
